### PR TITLE
Change layout to fix language selector

### PR DESCRIPTION
**Pull request by Thithic**
Hello, 
Following the discussion in #2 , I thought I'd give a try in fixing the layout for small screens.
The result I have for now looks like that : 
image
I basically just centered the "Visit Github", and let the language selector go in the top-right corner.

The "big screen" layout is also changed the same way.

Please, when you have time, could tell me if that suits you or not.
I can, of course rework it if you have a specific idea in mind :) 

Thank you

### CODE REVIEW

**Review by patrickgold — COMMENTED** [review]
Thanks a lot for your PR!

It looks pretty well I must say :)

> Please, when you have time, could tell me if that suits you or not.
I can, of course rework it if you have a specific idea in mind :)

The idea I had at the time was to just replace the "Visit GitHub repo" link with a clickable GitHub icon on mobile and then it should fit into one line (provided we reduce the horizontal header padding a bit).

If you want you can change it to this way, but I would also be okay with your solution for now :)

**Comment by Thithic** [comment]
Hello, 

Thank you for your review :) 

> The idea I had at the time was to just replace the "Visit GitHub repo" link with a clickable GitHub icon on mobile and then it should fit into one line (provided we reduce the horizontal header padding a bit).

Ah yes I see, I'll see if I manage to do that and I'll get back to you !

**Comment by Thithic** [comment]
Hello, 
I have changed the header design according (I think) to your view. Here is the result on big screen: 
image
and on small screen: 
image
The design works well with screen as little as 320px wide (tested with firefox developper tools)

Feel free to tell me what you think about it :)

**Review by patrickgold — APPROVED** [review]
Hey [Thithic](https://github.com/Thithic),

I am very sorry for not reviewing your PR for 3 months, I completely oversaw your awesome changes and now just stumbled on it by accident.

I have reviewed your changes and must say I really like them, they also seem to work very well with mobile screens.

As such I will merge in your changes, and again sorry for letting your PR collecting dust for so long!

**Comment by Thithic** [comment]
Hello Patrick, 

Thank you for the merge.
No worries, I can only imagine how Florisboard alone keeps you busy !

**Pull request merged**
